
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bunny_Mangrani
 */
public class ADMINEUPDATEATTENDENSE extends javax.swing.JFrame {

    /**
     * Creates new form ADMINEUPDATEATTENDENSE
     */
    public ADMINEUPDATEATTENDENSE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        LabelLecturerDOB7 = new javax.swing.JLabel();
        VIEWSTUDENTATTENDENCE = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        LabelLecturerID5 = new javax.swing.JLabel();
        LabelLecturerID6 = new javax.swing.JLabel();
        LabelLecturerID7 = new javax.swing.JLabel();
        REQUESTYEAR = new javax.swing.JTextField();
        REQUESTDATE = new javax.swing.JTextField();
        REQUESTMONTH = new javax.swing.JTextField();
        REQUESTNAME = new javax.swing.JTextField();
        LabelLecturerID1 = new javax.swing.JLabel();
        REQUESTATTENDENCE = new javax.swing.JComboBox<>();
        LabelLecturerID3 = new javax.swing.JLabel();
        CLEARATTENDENCE = new javax.swing.JButton();
        LabelLecturerID9 = new javax.swing.JLabel();
        REQUESTID = new javax.swing.JTextField();
        LabelLecturerDOB8 = new javax.swing.JLabel();
        UPDATESTUDENTATTENDENCE = new javax.swing.JButton();
        LabelLecturerDOB9 = new javax.swing.JLabel();
        CLEARSTUDENT3 = new javax.swing.JButton();
        LabelLecturerID10 = new javax.swing.JLabel();
        LabelLecturerID8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        btnLecturerExit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BACK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(36, 47, 65));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID NO:", "NAME:", "ATTENDENCE", "DAY", "MONTH", "YEAR", "REASON"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable4.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable4AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable4);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 710, 190));

        LabelLecturerDOB7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelLecturerDOB7.setText("VIEW ALL REQUEST");
        jPanel2.add(LabelLecturerDOB7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 140, 30));

        VIEWSTUDENTATTENDENCE.setBackground(new java.awt.Color(97, 212, 195));
        VIEWSTUDENTATTENDENCE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        VIEWSTUDENTATTENDENCE.setForeground(new java.awt.Color(102, 102, 102));
        VIEWSTUDENTATTENDENCE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture15.PNG"))); // NOI18N
        VIEWSTUDENTATTENDENCE.setText("SAVE");
        VIEWSTUDENTATTENDENCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VIEWSTUDENTATTENDENCEActionPerformed(evt);
            }
        });
        jPanel2.add(VIEWSTUDENTATTENDENCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 150, 30));

        jPanel3.setBackground(new java.awt.Color(36, 47, 65));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MODIFY STUDENT ATTENDENCE RECORD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(36, 47, 65));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelLecturerID5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelLecturerID5.setForeground(new java.awt.Color(204, 204, 204));
        LabelLecturerID5.setText("DATE:");
        jPanel4.add(LabelLecturerID5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 32));

        LabelLecturerID6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelLecturerID6.setForeground(new java.awt.Color(204, 204, 204));
        LabelLecturerID6.setText("MONTH:");
        jPanel4.add(LabelLecturerID6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, 32));

        LabelLecturerID7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelLecturerID7.setForeground(new java.awt.Color(204, 204, 204));
        LabelLecturerID7.setText("YEAR:");
        jPanel4.add(LabelLecturerID7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, 32));

        REQUESTYEAR.setBackground(new java.awt.Color(36, 47, 65));
        REQUESTYEAR.setForeground(new java.awt.Color(255, 255, 255));
        REQUESTYEAR.setToolTipText("");
        REQUESTYEAR.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        REQUESTYEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REQUESTYEARActionPerformed(evt);
            }
        });
        jPanel4.add(REQUESTYEAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 60, 30));

        REQUESTDATE.setBackground(new java.awt.Color(36, 47, 65));
        REQUESTDATE.setForeground(new java.awt.Color(255, 255, 255));
        REQUESTDATE.setToolTipText("");
        REQUESTDATE.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        REQUESTDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REQUESTDATEActionPerformed(evt);
            }
        });
        jPanel4.add(REQUESTDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 60, 30));

        REQUESTMONTH.setBackground(new java.awt.Color(36, 47, 65));
        REQUESTMONTH.setForeground(new java.awt.Color(255, 255, 255));
        REQUESTMONTH.setToolTipText("");
        REQUESTMONTH.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        REQUESTMONTH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REQUESTMONTHActionPerformed(evt);
            }
        });
        jPanel4.add(REQUESTMONTH, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 60, 30));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 390, 80));

        REQUESTNAME.setBackground(new java.awt.Color(36, 47, 65));
        REQUESTNAME.setForeground(new java.awt.Color(255, 255, 255));
        REQUESTNAME.setToolTipText("");
        REQUESTNAME.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        REQUESTNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REQUESTNAMEActionPerformed(evt);
            }
        });
        jPanel3.add(REQUESTNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 450, 30));

        LabelLecturerID1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelLecturerID1.setText("SAVE RECORD");
        jPanel3.add(LabelLecturerID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 100, 30));

        REQUESTATTENDENCE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "PRESENT", "ABSENT", "LATE", "ABSENT WITH REASON" }));
        jPanel3.add(REQUESTATTENDENCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 170, -1));

        LabelLecturerID3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelLecturerID3.setForeground(new java.awt.Color(204, 204, 204));
        LabelLecturerID3.setText("ATTENDENCE:");
        jPanel3.add(LabelLecturerID3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, 32));

        CLEARATTENDENCE.setBackground(new java.awt.Color(97, 212, 195));
        CLEARATTENDENCE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CLEARATTENDENCE.setForeground(new java.awt.Color(102, 102, 102));
        CLEARATTENDENCE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture15.PNG"))); // NOI18N
        CLEARATTENDENCE.setText("SAVE");
        CLEARATTENDENCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARATTENDENCEActionPerformed(evt);
            }
        });
        jPanel3.add(CLEARATTENDENCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 130, 30));

        LabelLecturerID9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelLecturerID9.setForeground(new java.awt.Color(204, 204, 204));
        LabelLecturerID9.setText("STUDENT ID: ");
        jPanel3.add(LabelLecturerID9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 90, 32));

        REQUESTID.setBackground(new java.awt.Color(36, 47, 65));
        REQUESTID.setForeground(new java.awt.Color(255, 255, 255));
        REQUESTID.setToolTipText("");
        REQUESTID.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        REQUESTID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REQUESTIDActionPerformed(evt);
            }
        });
        jPanel3.add(REQUESTID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 150, 30));

        LabelLecturerDOB8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelLecturerDOB8.setText("UPDATE");
        jPanel3.add(LabelLecturerDOB8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 70, 30));

        UPDATESTUDENTATTENDENCE.setBackground(new java.awt.Color(97, 212, 195));
        UPDATESTUDENTATTENDENCE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UPDATESTUDENTATTENDENCE.setForeground(new java.awt.Color(102, 102, 102));
        UPDATESTUDENTATTENDENCE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture15.PNG"))); // NOI18N
        UPDATESTUDENTATTENDENCE.setText("SAVE");
        UPDATESTUDENTATTENDENCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATESTUDENTATTENDENCEActionPerformed(evt);
            }
        });
        jPanel3.add(UPDATESTUDENTATTENDENCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 120, 30));

        LabelLecturerDOB9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelLecturerDOB9.setText("CLEAR");
        jPanel3.add(LabelLecturerDOB9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 50, 30));

        CLEARSTUDENT3.setBackground(new java.awt.Color(97, 212, 195));
        CLEARSTUDENT3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CLEARSTUDENT3.setForeground(new java.awt.Color(102, 102, 102));
        CLEARSTUDENT3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture15.PNG"))); // NOI18N
        CLEARSTUDENT3.setText("SAVE");
        CLEARSTUDENT3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARSTUDENT3ActionPerformed(evt);
            }
        });
        jPanel3.add(CLEARSTUDENT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 120, 30));

        LabelLecturerID10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelLecturerID10.setForeground(new java.awt.Color(204, 204, 204));
        LabelLecturerID10.setText("STUDENT NAME: ");
        jPanel3.add(LabelLecturerID10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 100, 32));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 710, 240));

        LabelLecturerID8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelLecturerID8.setForeground(new java.awt.Color(204, 204, 204));
        LabelLecturerID8.setText("Select \"VIEW ALL REQUEST BUTTON\" to see the student attendence: ");
        jPanel2.add(LabelLecturerID8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 480, 32));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 770, 560));

        jPanel1.setBackground(new java.awt.Color(97, 212, 195));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("UPDATE ATTENDENCE RECORD: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 310, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 250, 60));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 320, 40));

        btnLecturerExit.setText("EXIT");
        btnLecturerExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLecturerExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnLecturerExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 130, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("APU ATTENDENCE ");
        jLabel4.setToolTipText("");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("MANAGMENT SYSTEM");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/002-professor.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        BACK.setText("BACK");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });
        jPanel1.add(BACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 520, 110, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLecturerExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLecturerExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnLecturerExitActionPerformed

    private void jTable4AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable4AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable4AncestorAdded

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
     DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
        REQUESTID.setText(model.getValueAt(jTable4.getSelectedRow(),0).toString());
        REQUESTNAME.setText(model.getValueAt(jTable4.getSelectedRow(),1).toString());
        REQUESTATTENDENCE.setSelectedItem(model.getValueAt(jTable4.getSelectedRow(),2).toString());
        REQUESTDATE.setText(model.getValueAt(jTable4.getSelectedRow(),3).toString());
        REQUESTMONTH.setText(model.getValueAt(jTable4.getSelectedRow(),4).toString());
        REQUESTYEAR.setText(model.getValueAt(jTable4.getSelectedRow(),5).toString());
        

    }//GEN-LAST:event_jTable4MouseClicked

    private void VIEWSTUDENTATTENDENCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VIEWSTUDENTATTENDENCEActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
        //Lecturer1 lecturer = new Lecturer1();
        try{
            FileReader f=new FileReader("request.txt");
            BufferedReader bf=new BufferedReader(f);
            String line;
            while((line=bf.readLine())!=null){
                model.addRow(line.split(","));
                
                //model.addRow(new Object[]{lecturer.getidno(), lecturer.getname(), lecturer.getpassword(), lecturer.getgender(), lecturer.getnationality(), lecturer.getdob()});
            }
            bf.close();
        }catch(Exception e){}
    }//GEN-LAST:event_VIEWSTUDENTATTENDENCEActionPerformed

    private void REQUESTNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REQUESTNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_REQUESTNAMEActionPerformed

    private void CLEARATTENDENCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARATTENDENCEActionPerformed

    }//GEN-LAST:event_CLEARATTENDENCEActionPerformed

    private void REQUESTIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REQUESTIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_REQUESTIDActionPerformed

    private void UPDATESTUDENTATTENDENCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATESTUDENTATTENDENCEActionPerformed
        String id =  REQUESTID.getText();
        String date = REQUESTDATE.getText();
        String attendence = (String) REQUESTATTENDENCE.getSelectedItem();;
            
        ArrayList<ATTENDENCESTUDENT> Studentrecord = new ArrayList<>();
     
        if (date.isEmpty()) {JOptionPane.showMessageDialog(null,  "SELECT");
            JOptionPane.showMessageDialog(this, " Please Fill all fields");}
        else{
        try {
            File f = new File ("ATTENDENCERECORD.txt");
            FileReader fr = new FileReader(f);
            BufferedReader br = new BufferedReader(fr);
            String data;
            ATTENDENCESTUDENT UpdateATTENDENCE;
            
            while ((data = br.readLine()) != null) {
                    
                        UpdateATTENDENCE = new ATTENDENCESTUDENT(data);
                        if (UpdateATTENDENCE.getAId().equals(id)&&UpdateATTENDENCE.getADate().equals(date)) {
                          
                          
                            UpdateATTENDENCE.setAClassAttendence(attendence);
                            
                             }
                        Studentrecord.add(UpdateATTENDENCE);
                    }
            try (PrintWriter printwriter = new PrintWriter(new FileWriter(f, false))) {
                    Studentrecord.forEach((student) -> {
                        printwriter.println(student.toString());
                        
                        
                    });
                    JOptionPane.showMessageDialog(this, "Student Updated Succesfully");
                    
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }

            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
        
              }   catch (IOException ex) { 
                    Logger.getLogger(MODIFYSTUDENT.class.getName()).log(Level.SEVERE, null, ex);
                } 
        }
    }//GEN-LAST:event_UPDATESTUDENTATTENDENCEActionPerformed

    private void CLEARSTUDENT3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARSTUDENT3ActionPerformed
        REQUESTID.setText("");
        REQUESTNAME.setText("");
        REQUESTATTENDENCE.setSelectedItem("SELECT");
        REQUESTDATE.setText("");
        REQUESTMONTH.setText("");
        REQUESTYEAR.setText("");
              // TODO add your handling code here:
    }//GEN-LAST:event_CLEARSTUDENT3ActionPerformed

    private void REQUESTYEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REQUESTYEARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_REQUESTYEARActionPerformed

    private void REQUESTDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REQUESTDATEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_REQUESTDATEActionPerformed

    private void REQUESTMONTHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REQUESTMONTHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_REQUESTMONTHActionPerformed

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
        close();
        ADDSTUDENT goback = new ADDSTUDENT();
        goback.setVisible(true);
    }//GEN-LAST:event_BACKActionPerformed
    private void close() {
        WindowEvent closewindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closewindow);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADMINEUPDATEATTENDENSE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADMINEUPDATEATTENDENSE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADMINEUPDATEATTENDENSE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADMINEUPDATEATTENDENSE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADMINEUPDATEATTENDENSE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACK;
    private javax.swing.JButton CLEARATTENDENCE;
    private javax.swing.JButton CLEARSTUDENT3;
    private javax.swing.JLabel LabelLecturerDOB7;
    private javax.swing.JLabel LabelLecturerDOB8;
    private javax.swing.JLabel LabelLecturerDOB9;
    private javax.swing.JLabel LabelLecturerID1;
    private javax.swing.JLabel LabelLecturerID10;
    private javax.swing.JLabel LabelLecturerID3;
    private javax.swing.JLabel LabelLecturerID5;
    private javax.swing.JLabel LabelLecturerID6;
    private javax.swing.JLabel LabelLecturerID7;
    private javax.swing.JLabel LabelLecturerID8;
    private javax.swing.JLabel LabelLecturerID9;
    private javax.swing.JComboBox<String> REQUESTATTENDENCE;
    private javax.swing.JTextField REQUESTDATE;
    private javax.swing.JTextField REQUESTID;
    private javax.swing.JTextField REQUESTMONTH;
    private javax.swing.JTextField REQUESTNAME;
    private javax.swing.JTextField REQUESTYEAR;
    private javax.swing.JButton UPDATESTUDENTATTENDENCE;
    private javax.swing.JButton VIEWSTUDENTATTENDENCE;
    private javax.swing.JButton btnLecturerExit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables
}
