
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bunny_Mangrani
 */
public class LECTURERLOGINFORM extends javax.swing.JFrame {

    /**
     * Creates new form LECTURERLOGINFORM
     */
    public LECTURERLOGINFORM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Username2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Password2 = new javax.swing.JPasswordField();
        butnClear1 = new javax.swing.JButton();
        Login = new javax.swing.JButton();
        butnExit1 = new javax.swing.JButton();
        BACK = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apu_still01_entrance_0.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("LECTURER LOGIN FORM: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 350, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("LECTURERID: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 120, -1));

        Username2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Username2ActionPerformed(evt);
            }
        });
        getContentPane().add(Username2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 180, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("PASSWORD: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 120, -1));

        Password2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password2ActionPerformed(evt);
            }
        });
        getContentPane().add(Password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 180, 30));

        butnClear1.setText("CLEAR");
        butnClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butnClear1ActionPerformed(evt);
            }
        });
        getContentPane().add(butnClear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 103, -1));

        Login.setText("LOGIN");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 103, -1));

        butnExit1.setText("EXIT");
        butnExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butnExit1ActionPerformed(evt);
            }
        });
        getContentPane().add(butnExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 110, -1));

        BACK.setText("BACK");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });
        getContentPane().add(BACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 110, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apu_still01_entrance_0.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Username2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username2ActionPerformed

    }//GEN-LAST:event_Username2ActionPerformed
    private void butnExit1ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        System.exit(0);
    }  
    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {                                     
        close();
        APU goback = new APU();
        goback.setVisible(true);
    }
    
    private void Password2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password2ActionPerformed

    private void butnClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butnClear1ActionPerformed
        Username2.setText("");
        Password2.setText("");
    }//GEN-LAST:event_butnClear1ActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        String username = Username2.getText();
        String password = Password2.getText();
        try{
            boolean flag=false;
            FileReader fw = new FileReader("bunny.txt");
            BufferedReader bw = new BufferedReader(fw);
            String line;//=bw.readLine();
            Lecturer1 std;
            while((line=bw.readLine())!=null){
                std = new Lecturer1(line);  //((line = bw.readLine()) != null)
                if(std.getidno().equals(username)&&std.getpassword().equals(password)){
                    flag = true;
                    TEACHERINFORMATION view = new TEACHERINFORMATION();
                    view.setVisible(true);

                }
            }
            if(flag==false){JOptionPane.showMessageDialog(null,"wrong id or password");}
                    Username2.setText("");
                    Password2.setText("");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(STUDENTLOGINFORM.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(STUDENTLOGINFORM.class.getName()).log(Level.SEVERE, null, ex);
        }

        }

        //  } catch (FileNotFoundException ex) {
        //    Logger.getLogger(STUDENTLOGINFORM.class.getName()).log(Level.SEVERE, null, ex);

        /*
        String Username = Username2.getText();
        String Password = Password2.getText();

        if(Username.contains("101") && Password.contains("1234")){
            WELCOMESTUDENT student = new WELCOMESTUDENT (Username);
            student.setVisible(true);

        }else {
            JOptionPane.showMessageDialog(null, "Sorry, This Password is wrong       \nClick Ok & Try Again, Thanks! ", "WRONG PASSWORD", JOptionPane.ERROR_MESSAGE);
            Username2.setText("");
            Password2.setText("");

        }
    }//GEN-LAST:event_LoginActionPerformed

    private void butnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butnExit1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_butnExit1ActionPerformed

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
        close();
        ADMININFORMATION goback = new ADMININFORMATION();
        goback.setVisible(true);
    }//GEN-LAST:event_BACKActionPerformed

    /**
     * @param args the command line arguments
     */
    private void close() {
        WindowEvent closewindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closewindow);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LECTURERLOGINFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LECTURERLOGINFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LECTURERLOGINFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LECTURERLOGINFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LECTURERLOGINFORM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACK;
    private javax.swing.JButton Login;
    private javax.swing.JPasswordField Password2;
    private javax.swing.JTextField Username2;
    private javax.swing.JButton butnClear1;
    private javax.swing.JButton butnExit1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
