
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bunny_Mangrani
 */
public class SEARCHLECTURER extends javax.swing.JFrame {
    public SEARCHLECTURER() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        IDSEARCH = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        CLEARSEARCH = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        labelLecturerSearch = new javax.swing.JLabel();
        labelLecturerSearch1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btnLecturerSID = new javax.swing.JTextField();
        labelLecturerSearch2 = new javax.swing.JLabel();
        btnLecturerSName = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        labelLecturerSearch3 = new javax.swing.JLabel();
        btnLecturerSPassword = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        labelLecturerSearch4 = new javax.swing.JLabel();
        btnLecturerSDOB = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        labelLecturerSearch5 = new javax.swing.JLabel();
        labelLecturerSearch6 = new javax.swing.JLabel();
        btnLecturerSNat = new javax.swing.JTextField();
        btnLecturerSFemale = new javax.swing.JCheckBox();
        btnLecturerSMale = new javax.swing.JCheckBox();
        jSeparator12 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        btnLecturerExit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        BACK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(36, 47, 65));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Enter the Lecturer ID Number & Click Search: ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 330, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 230, 20));

        IDSEARCH.setBackground(new java.awt.Color(36, 47, 65));
        IDSEARCH.setForeground(new java.awt.Color(255, 255, 255));
        IDSEARCH.setBorder(null);
        IDSEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDSEARCHActionPerformed(evt);
            }
        });
        jPanel2.add(IDSEARCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 230, 20));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("SEARCH");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 70, 30));

        jButton1.setBackground(new java.awt.Color(97, 212, 195));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture15.PNG"))); // NOI18N
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 118, 30));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("CLEAR");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 60, 30));

        CLEARSEARCH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture15.PNG"))); // NOI18N
        CLEARSEARCH.setText("CLEAR");
        CLEARSEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARSEARCHActionPerformed(evt);
            }
        });
        jPanel2.add(CLEARSEARCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 120, 30));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Lecturer Profile: ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 190, -1));

        labelLecturerSearch.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        labelLecturerSearch.setForeground(new java.awt.Color(204, 204, 204));
        labelLecturerSearch.setText("Name: ");
        jPanel2.add(labelLecturerSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 60, 30));

        labelLecturerSearch1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        labelLecturerSearch1.setForeground(new java.awt.Color(204, 204, 204));
        labelLecturerSearch1.setText("LECTURER ID: ");
        jPanel2.add(labelLecturerSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 100, -1));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 240, 20));

        btnLecturerSID.setBackground(new java.awt.Color(36, 47, 65));
        btnLecturerSID.setForeground(new java.awt.Color(255, 255, 255));
        btnLecturerSID.setBorder(null);
        btnLecturerSID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLecturerSIDActionPerformed(evt);
            }
        });
        jPanel2.add(btnLecturerSID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 250, 20));

        labelLecturerSearch2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        labelLecturerSearch2.setForeground(new java.awt.Color(204, 204, 204));
        labelLecturerSearch2.setText("ID No: ");
        jPanel2.add(labelLecturerSearch2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 60, 30));

        btnLecturerSName.setBackground(new java.awt.Color(36, 47, 65));
        btnLecturerSName.setForeground(new java.awt.Color(255, 255, 255));
        btnLecturerSName.setBorder(null);
        btnLecturerSName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLecturerSNameActionPerformed(evt);
            }
        });
        jPanel2.add(btnLecturerSName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 250, 20));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 240, 20));

        labelLecturerSearch3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        labelLecturerSearch3.setForeground(new java.awt.Color(204, 204, 204));
        labelLecturerSearch3.setText("Password: ");
        jPanel2.add(labelLecturerSearch3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 70, 30));

        btnLecturerSPassword.setBackground(new java.awt.Color(36, 47, 65));
        btnLecturerSPassword.setForeground(new java.awt.Color(255, 255, 255));
        btnLecturerSPassword.setBorder(null);
        btnLecturerSPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLecturerSPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(btnLecturerSPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 260, 20));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 240, 20));

        labelLecturerSearch4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        labelLecturerSearch4.setForeground(new java.awt.Color(204, 204, 204));
        labelLecturerSearch4.setText("DOB: ");
        jPanel2.add(labelLecturerSearch4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 70, 30));

        btnLecturerSDOB.setBackground(new java.awt.Color(36, 47, 65));
        btnLecturerSDOB.setForeground(new java.awt.Color(255, 255, 255));
        btnLecturerSDOB.setBorder(null);
        btnLecturerSDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLecturerSDOBActionPerformed(evt);
            }
        });
        jPanel2.add(btnLecturerSDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 260, 20));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 240, 20));

        labelLecturerSearch5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        labelLecturerSearch5.setForeground(new java.awt.Color(204, 204, 204));
        labelLecturerSearch5.setText("Gender:");
        jPanel2.add(labelLecturerSearch5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 70, 20));

        labelLecturerSearch6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        labelLecturerSearch6.setForeground(new java.awt.Color(204, 204, 204));
        labelLecturerSearch6.setText("Nationality: ");
        jPanel2.add(labelLecturerSearch6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 70, 30));

        btnLecturerSNat.setBackground(new java.awt.Color(36, 47, 65));
        btnLecturerSNat.setForeground(new java.awt.Color(255, 255, 255));
        btnLecturerSNat.setBorder(null);
        btnLecturerSNat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLecturerSNatActionPerformed(evt);
            }
        });
        jPanel2.add(btnLecturerSNat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 260, 20));

        btnLecturerSFemale.setBackground(new java.awt.Color(36, 47, 65));
        btnLecturerSFemale.setForeground(new java.awt.Color(204, 204, 204));
        btnLecturerSFemale.setText("FEMALE");
        btnLecturerSFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLecturerSFemaleActionPerformed(evt);
            }
        });
        jPanel2.add(btnLecturerSFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, -1, 20));

        btnLecturerSMale.setBackground(new java.awt.Color(36, 47, 65));
        btnLecturerSMale.setForeground(new java.awt.Color(204, 204, 204));
        btnLecturerSMale.setText("MALE");
        btnLecturerSMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLecturerSMaleActionPerformed(evt);
            }
        });
        jPanel2.add(btnLecturerSMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 60, 20));
        jPanel2.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 240, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 430, 520));

        jPanel1.setBackground(new java.awt.Color(97, 212, 195));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SEARCH LECTURERS:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 200, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/searcher (1).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 290, 270));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 250, 40));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 320, 40));

        btnLecturerExit.setText("EXIT");
        btnLecturerExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLecturerExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnLecturerExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 130, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("MANAGMENT SYSTEM");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("APU ATTENDENCE ");
        jLabel7.setToolTipText("");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 30));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 320, 40));

        BACK.setText("BACK");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });
        jPanel1.add(BACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDSEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDSEARCHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDSEARCHActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        FileReader fr = null;
        String LecturerID= IDSEARCH.getText();
        String genderrecord;
        
        if (LecturerID.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter an ID First"); }
          else{
        try {
            File Lecturer = new File ("bunny.txt");
            fr = new FileReader(Lecturer);
            BufferedReader br = new BufferedReader(fr);
            String data;
            Lecturer1 lecturer;
            
            while ((data = br.readLine()) != null){
             lecturer = new Lecturer1(data);
            
            
            
            
           
                if (lecturer.getidno().equals(LecturerID))
                {
                    
                    btnLecturerSID.setText(lecturer.getidno());
                    btnLecturerSName.setText(lecturer.getname());
                    btnLecturerSPassword.setText(lecturer.getpassword());
                    btnLecturerSNat.setText(lecturer.getnationality());
                    btnLecturerSDOB.setText(lecturer.getdob());
                    genderrecord = lecturer.getgender();
                   
                    if (genderrecord.equals("Male")){ // checks the user gender
                    btnLecturerSMale.setSelected(true);
                    btnLecturerSFemale.setSelected(false);} 
                    else {btnLecturerSFemale.setSelected(true);
                    btnLecturerSMale.setSelected(false);}
                   
                    // Switch case to identify the selcted course
                    
                  JOptionPane.showMessageDialog(null,"Data is searched successfully");
                    return;
                    
                    
                }//if(!lecturer.getidno().equals(LecturerID))
                   //     {
                    //JOptionPane.showMessageDialog(null,"Record not founded");
                    //return;
                //}
                
            
        
            }
            
            
        } catch (FileNotFoundException ex) {
            
      
        }   catch (IOException ex) {
                Logger.getLogger(SEARCHLECTURER.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
            try {
                fr.close();
                
                
          //  } catch (IOException ex) {
            //    Logger.getLogger(Admin_SearchRecords.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(SEARCHLECTURER.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        }
    
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        /*   String search = IDSEARCH.getText();
       Scanner sc = new Scanner(System.in);
       try{ File f = new File("bunny.txt");
       sc= new Scanner(f);
      
        /*FileReader fr = new FileReader(f);
        BufferedReader br = new BufferedReader(fr);*/
      /*  while(sc.hasNextLine()){
            String line=sc.nextLine();
            String[] wordof=line.split(" ");
            for(String word:wordof){
            if(word.equals(search)){
                jTextArea1.append(line); 
                jTextArea1.append("\n");
                jTextArea1.append(sc.nextLine());
                jTextArea1.append("\n");
                jTextArea1.append(sc.nextLine());
                jTextArea1.append("\n");
                jTextArea1.append(sc.nextLine());
                jTextArea1.append("\n");
                jTextArea1.append(sc.nextLine());
                jTextArea1.append("\n");
                jTextArea1.append(sc.nextLine());
                jTextArea1.append("\n");
                
               
         
                
                
            }
            }
            //line=br.readLine();
        }
       sc.close();
       }catch(Exception ee){
        JOptionPane.showMessageDialog(null,"error");
    }   */  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CLEARSEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARSEARCHActionPerformed
        btnLecturerSID.setText("");
        btnLecturerSName.setText("");
        btnLecturerSPassword.setText("");
        btnLecturerSMale.setSelected(false);
        btnLecturerSFemale.setSelected(false);
        btnLecturerSNat.setText("");
        btnLecturerSDOB.setText("");
    }//GEN-LAST:event_CLEARSEARCHActionPerformed

    private void btnLecturerExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLecturerExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnLecturerExitActionPerformed

    private void btnLecturerSIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLecturerSIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLecturerSIDActionPerformed

    private void btnLecturerSNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLecturerSNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLecturerSNameActionPerformed

    private void btnLecturerSPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLecturerSPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLecturerSPasswordActionPerformed

    private void btnLecturerSDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLecturerSDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLecturerSDOBActionPerformed

    private void btnLecturerSNatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLecturerSNatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLecturerSNatActionPerformed

    private void btnLecturerSMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLecturerSMaleActionPerformed
        btnLecturerSMale.setSelected(true);
        btnLecturerSFemale.setSelected(false);
    }//GEN-LAST:event_btnLecturerSMaleActionPerformed

    private void btnLecturerSFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLecturerSFemaleActionPerformed
        btnLecturerSMale.setSelected(false);
        btnLecturerSFemale.setSelected(true);
    }//GEN-LAST:event_btnLecturerSFemaleActionPerformed

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
        close();
        ADDTEACHER goback = new ADDTEACHER();
        goback.setVisible(true);
    }//GEN-LAST:event_BACKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SEARCHLECTURER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SEARCHLECTURER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SEARCHLECTURER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SEARCHLECTURER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SEARCHLECTURER().setVisible(true);
            }
        });
    }
    private void close() {
        WindowEvent closewindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closewindow);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACK;
    private javax.swing.JButton CLEARSEARCH;
    private javax.swing.JTextField IDSEARCH;
    private javax.swing.JButton btnLecturerExit;
    private javax.swing.JTextField btnLecturerSDOB;
    private javax.swing.JCheckBox btnLecturerSFemale;
    private javax.swing.JTextField btnLecturerSID;
    private javax.swing.JCheckBox btnLecturerSMale;
    private javax.swing.JTextField btnLecturerSName;
    private javax.swing.JTextField btnLecturerSNat;
    private javax.swing.JTextField btnLecturerSPassword;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel labelLecturerSearch;
    private javax.swing.JLabel labelLecturerSearch1;
    private javax.swing.JLabel labelLecturerSearch2;
    private javax.swing.JLabel labelLecturerSearch3;
    private javax.swing.JLabel labelLecturerSearch4;
    private javax.swing.JLabel labelLecturerSearch5;
    private javax.swing.JLabel labelLecturerSearch6;
    // End of variables declaration//GEN-END:variables
}
