
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bunny_Mangrani
 */
public class STUDENTATTENDENCE extends javax.swing.JFrame {

    /**
     * Creates new form STUDENTATTENDENCE
     */
    public STUDENTATTENDENCE() {
        initComponents();
    }
            public STUDENTATTENDENCE(String Username){
            this.Username=Username;
            initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        LabelLecturerID5 = new javax.swing.JLabel();
        LabelLecturerID6 = new javax.swing.JLabel();
        LabelLecturerID7 = new javax.swing.JLabel();
        RequestYear = new javax.swing.JTextField();
        RequestDate = new javax.swing.JTextField();
        RequestMonth = new javax.swing.JTextField();
        RequestName = new javax.swing.JTextField();
        LabelLecturerID1 = new javax.swing.JLabel();
        LabelLecturerID3 = new javax.swing.JLabel();
        LabelLecturerID8 = new javax.swing.JLabel();
        CLEARATTENDENCE = new javax.swing.JButton();
        LabelLecturerID9 = new javax.swing.JLabel();
        RequestId = new javax.swing.JTextField();
        RequestAttendence = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RequestReason = new javax.swing.JTextArea();
        LabelLecturerDOB6 = new javax.swing.JLabel();
        SUBMITREQUEST = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BACK = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        btnLecturerExit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(36, 47, 65));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID NO:", "NAME:", "GENDER:", "START CLASS:", "DURATION CLASS: ", "ATTENDENCE", "MODULE NAME", "DAY", "MONTH", "YEAR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable3AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 810, 190));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Press, View button to see all records of Students' Attendence, & den Modify.");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 490, -1));

        jPanel3.setBackground(new java.awt.Color(36, 47, 65));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "VIEW YOUR INFORMATION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(36, 47, 65));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelLecturerID5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelLecturerID5.setForeground(new java.awt.Color(204, 204, 204));
        LabelLecturerID5.setText("DATE:");
        jPanel4.add(LabelLecturerID5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 32));

        LabelLecturerID6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelLecturerID6.setForeground(new java.awt.Color(204, 204, 204));
        LabelLecturerID6.setText("MONTH:");
        jPanel4.add(LabelLecturerID6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, 32));

        LabelLecturerID7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelLecturerID7.setForeground(new java.awt.Color(204, 204, 204));
        LabelLecturerID7.setText("YEAR:");
        jPanel4.add(LabelLecturerID7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, 32));

        RequestYear.setEditable(false);
        RequestYear.setBackground(new java.awt.Color(36, 47, 65));
        RequestYear.setForeground(new java.awt.Color(255, 255, 255));
        RequestYear.setToolTipText("");
        RequestYear.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        RequestYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestYearActionPerformed(evt);
            }
        });
        jPanel4.add(RequestYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 60, 30));

        RequestDate.setEditable(false);
        RequestDate.setBackground(new java.awt.Color(36, 47, 65));
        RequestDate.setForeground(new java.awt.Color(255, 255, 255));
        RequestDate.setToolTipText("");
        RequestDate.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        RequestDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestDateActionPerformed(evt);
            }
        });
        jPanel4.add(RequestDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 60, 30));

        RequestMonth.setEditable(false);
        RequestMonth.setBackground(new java.awt.Color(36, 47, 65));
        RequestMonth.setForeground(new java.awt.Color(255, 255, 255));
        RequestMonth.setToolTipText("");
        RequestMonth.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        RequestMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestMonthActionPerformed(evt);
            }
        });
        jPanel4.add(RequestMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 60, 30));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 470, 80));

        RequestName.setEditable(false);
        RequestName.setBackground(new java.awt.Color(36, 47, 65));
        RequestName.setForeground(new java.awt.Color(255, 255, 255));
        RequestName.setToolTipText("");
        RequestName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        RequestName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestNameActionPerformed(evt);
            }
        });
        jPanel3.add(RequestName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 360, 30));

        LabelLecturerID1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelLecturerID1.setText("SAVE RECORD");
        jPanel3.add(LabelLecturerID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 100, 30));

        LabelLecturerID3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelLecturerID3.setForeground(new java.awt.Color(204, 204, 204));
        LabelLecturerID3.setText("ATTENDENCE:");
        jPanel3.add(LabelLecturerID3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 100, 32));

        LabelLecturerID8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelLecturerID8.setForeground(new java.awt.Color(204, 204, 204));
        LabelLecturerID8.setText("STUDENT NAME: ");
        jPanel3.add(LabelLecturerID8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 100, 32));

        CLEARATTENDENCE.setBackground(new java.awt.Color(97, 212, 195));
        CLEARATTENDENCE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CLEARATTENDENCE.setForeground(new java.awt.Color(102, 102, 102));
        CLEARATTENDENCE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture15.PNG"))); // NOI18N
        CLEARATTENDENCE.setText("SAVE");
        CLEARATTENDENCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARATTENDENCEActionPerformed(evt);
            }
        });
        jPanel3.add(CLEARATTENDENCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 130, 30));

        LabelLecturerID9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelLecturerID9.setForeground(new java.awt.Color(204, 204, 204));
        LabelLecturerID9.setText("STUDENT ID: ");
        jPanel3.add(LabelLecturerID9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 90, 32));

        RequestId.setEditable(false);
        RequestId.setBackground(new java.awt.Color(36, 47, 65));
        RequestId.setForeground(new java.awt.Color(255, 255, 255));
        RequestId.setToolTipText("");
        RequestId.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        RequestId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestIdActionPerformed(evt);
            }
        });
        jPanel3.add(RequestId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 120, 30));

        RequestAttendence.setEditable(false);
        RequestAttendence.setBackground(new java.awt.Color(36, 47, 65));
        RequestAttendence.setForeground(new java.awt.Color(255, 255, 255));
        RequestAttendence.setToolTipText("");
        RequestAttendence.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        RequestAttendence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestAttendenceActionPerformed(evt);
            }
        });
        jPanel3.add(RequestAttendence, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 150, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 540, 240));

        jPanel5.setBackground(new java.awt.Color(36, 47, 65));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "YOUR REASON", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RequestReason.setColumns(20);
        RequestReason.setRows(5);
        jScrollPane1.setViewportView(RequestReason);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 26, 250, 160));

        LabelLecturerDOB6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelLecturerDOB6.setText("SUBMIT");
        jPanel5.add(LabelLecturerDOB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 50, 30));

        SUBMITREQUEST.setBackground(new java.awt.Color(97, 212, 195));
        SUBMITREQUEST.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SUBMITREQUEST.setForeground(new java.awt.Color(102, 102, 102));
        SUBMITREQUEST.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture15.PNG"))); // NOI18N
        SUBMITREQUEST.setText("SAVE");
        SUBMITREQUEST.setBorder(null);
        SUBMITREQUEST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUBMITREQUESTActionPerformed(evt);
            }
        });
        jPanel5.add(SUBMITREQUEST, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 120, 30));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 280, 240));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 870, 520));

        jPanel1.setBackground(new java.awt.Color(97, 212, 195));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ADD NEW STUDENT:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 200, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/002-professor.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        BACK.setText("BACK");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });
        jPanel1.add(BACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 140, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 250, 40));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 320, 40));

        btnLecturerExit.setText("EXIT");
        btnLecturerExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLecturerExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnLecturerExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 130, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("APU ATTENDENCE ");
        jLabel4.setToolTipText("");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("MANAGMENT SYSTEM");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLecturerExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLecturerExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnLecturerExitActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
            DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        RequestName.setText(model.getValueAt(jTable3.getSelectedRow(),1).toString());
        RequestId.setText(model.getValueAt(jTable3.getSelectedRow(),0).toString());
        RequestAttendence.setText(model.getValueAt(jTable3.getSelectedRow(),5).toString());
        RequestDate.setText(model.getValueAt(jTable3.getSelectedRow(),7).toString());
        RequestMonth.setText(model.getValueAt(jTable3.getSelectedRow(),8).toString());
        RequestYear.setText(model.getValueAt(jTable3.getSelectedRow(),9).toString());
    }//GEN-LAST:event_jTable3MouseClicked
    
    
    
    
    private void jTable3AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable3AncestorAdded
    DefaultTableModel model1 = (DefaultTableModel) jTable3.getModel();
        
        try{
            System.out.println(Username);
            FileReader f=new FileReader("ATTENDENCERECORD.txt");
            BufferedReader bf=new BufferedReader(f);
            String line;
            while((line=bf.readLine())!=null){
                ATTENDENCESTUDENT student = new ATTENDENCESTUDENT(line);
                if(student.getAId().equals(Username)){
                model1.addRow(line.split(","));}
                //model.addRow(new Object[]{lecturer.getidno(), lecturer.getname(), lecturer.getpassword(), lecturer.getgender(), lecturer.getnationality(), lecturer.getdob()});
            }
            bf.close();
        }catch(Exception e){}
    }//GEN-LAST:event_jTable3AncestorAdded

    private void RequestNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestNameActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_RequestNameActionPerformed

    private void CLEARATTENDENCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARATTENDENCEActionPerformed

    }//GEN-LAST:event_CLEARATTENDENCEActionPerformed

    private void RequestYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RequestYearActionPerformed

    private void RequestIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RequestIdActionPerformed

    private void RequestAttendenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestAttendenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RequestAttendenceActionPerformed

    private void RequestDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RequestDateActionPerformed

    private void RequestMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RequestMonthActionPerformed

    private void SUBMITREQUESTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUBMITREQUESTActionPerformed
        String name = RequestName.getText();
        String id = RequestId.getText();
        String attendence = RequestAttendence.getText();
        String date = RequestDate.getText();
        String month = RequestMonth.getText();
        String year = RequestYear.getText();
        String reason = RequestReason.getText();
        
        if(reason.isEmpty()){JOptionPane.showMessageDialog(null, "Please Spicify the Reason.");}
        else if(id.isEmpty()){JOptionPane.showMessageDialog(null, "Please, Select your record. ");}
        else{
        try{
            File f = new File("request.txt");
            PrintWriter bw = new PrintWriter(new FileWriter(f,true));
            bw.write(id);
            bw.write(",");
            bw.write(name);
            bw.write(",");
            bw.write(attendence);
            bw.write(",");
            bw.write(date);
            bw.write(",");
            bw.write(month);
            bw.write(",");
            bw.write(year);
            bw.write(",");
            bw.write(reason);
            bw.write("\n");
            bw.close();
            JOptionPane.showMessageDialog(null, "Your Request is submit Successfully.");
            RequestReason.setText(null);
            
        }catch(Exception e){JOptionPane.showMessageDialog(null, "Something Wrong" );}
        }
    }//GEN-LAST:event_SUBMITREQUESTActionPerformed

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
        close();
        WELCOMESTUDENT goback = new WELCOMESTUDENT();
        goback.setVisible(true);
    }//GEN-LAST:event_BACKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(STUDENTATTENDENCE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(STUDENTATTENDENCE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(STUDENTATTENDENCE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(STUDENTATTENDENCE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new STUDENTATTENDENCE().setVisible(true);
            }
        });
    }
     private void close() {
        WindowEvent closewindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closewindow);
    }

    private String Username;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACK;
    private javax.swing.JButton CLEARATTENDENCE;
    private javax.swing.JLabel LabelLecturerDOB6;
    private javax.swing.JLabel LabelLecturerID1;
    private javax.swing.JLabel LabelLecturerID3;
    private javax.swing.JLabel LabelLecturerID5;
    private javax.swing.JLabel LabelLecturerID6;
    private javax.swing.JLabel LabelLecturerID7;
    private javax.swing.JLabel LabelLecturerID8;
    private javax.swing.JLabel LabelLecturerID9;
    private javax.swing.JTextField RequestAttendence;
    private javax.swing.JTextField RequestDate;
    private javax.swing.JTextField RequestId;
    private javax.swing.JTextField RequestMonth;
    private javax.swing.JTextField RequestName;
    private javax.swing.JTextArea RequestReason;
    private javax.swing.JTextField RequestYear;
    private javax.swing.JButton SUBMITREQUEST;
    private javax.swing.JButton btnLecturerExit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables

   // private void JOptionMessageDialog(Object object, String please_Spicify_the_Reason) {
     //   throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    //}
}
