/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bunny_Mangrani
 */
public class TEACHER extends javax.swing.JFrame {

    /**
     * Creates new form TEACHER
     */
    public TEACHER() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExit = new javax.swing.JButton();
        ATTENDENCE = new javax.swing.JButton();
        VIEWINTAKEVISE = new javax.swing.JButton();
        MODIFYSTUDENT = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnAdd3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 111, -1));

        ATTENDENCE.setText("ATTENDENCE");
        ATTENDENCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ATTENDENCEActionPerformed(evt);
            }
        });
        getContentPane().add(ATTENDENCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 200, 39));

        VIEWINTAKEVISE.setText("VIEW INTAKEVISE STUDENT");
        VIEWINTAKEVISE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VIEWINTAKEVISEActionPerformed(evt);
            }
        });
        getContentPane().add(VIEWINTAKEVISE, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 200, 39));

        MODIFYSTUDENT.setText("MODIFY STUDENT");
        MODIFYSTUDENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MODIFYSTUDENTActionPerformed(evt);
            }
        });
        getContentPane().add(MODIFYSTUDENT, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 200, 39));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("WELCOME TO LECTURER PAGE:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 420, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apu_still01_entrance_0.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 380));

        btnAdd3.setText("ADD");
        btnAdd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 146, 39));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VIEWINTAKEVISEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VIEWINTAKEVISEActionPerformed
    TEACHERVIEWSTUDENT Teacher = new TEACHERVIEWSTUDENT ();
     Teacher.setVisible(true);
    }//GEN-LAST:event_VIEWINTAKEVISEActionPerformed

    private void MODIFYSTUDENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODIFYSTUDENTActionPerformed
    TEACHERMODIFYSTUDENT Teacher = new TEACHERMODIFYSTUDENT ();
     Teacher.setVisible(true);
    }//GEN-LAST:event_MODIFYSTUDENTActionPerformed

    private void btnAdd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd3ActionPerformed
    TEACHERATTENDENCE Teacher = new TEACHERATTENDENCE ();
     Teacher.setVisible(true);
    }//GEN-LAST:event_btnAdd3ActionPerformed

    private void ATTENDENCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ATTENDENCEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ATTENDENCEActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);

    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TEACHER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TEACHER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TEACHER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TEACHER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TEACHER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ATTENDENCE;
    private javax.swing.JButton MODIFYSTUDENT;
    private javax.swing.JButton VIEWINTAKEVISE;
    private javax.swing.JButton btnAdd3;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
