
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bunny_Mangrani
 */
public class TEACHERMODIFYSTUDENT extends javax.swing.JFrame {

    /**
     * Creates new form TEACHERMODIFYSTUDENT
     */
    public TEACHERMODIFYSTUDENT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        LabelLecturerDOB7 = new javax.swing.JLabel();
        LabelLecturerDOB6 = new javax.swing.JLabel();
        CLEARSTUDENTATTENDENCE = new javax.swing.JButton();
        VIEWSTUDENTATTENDENCE = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        LabelLecturerID5 = new javax.swing.JLabel();
        DATE = new javax.swing.JComboBox<>();
        LabelLecturerID6 = new javax.swing.JLabel();
        MONTH = new javax.swing.JComboBox<>();
        YEAR = new javax.swing.JComboBox<>();
        LabelLecturerID7 = new javax.swing.JLabel();
        LabelLecturerName = new javax.swing.JLabel();
        ATTENDENCEGENDER = new javax.swing.JTextField();
        ATTENDENSENAME = new javax.swing.JTextField();
        CLASSTART = new javax.swing.JComboBox<>();
        LabelLecturerID1 = new javax.swing.JLabel();
        LabelLecturerID2 = new javax.swing.JLabel();
        CLASSDURATION = new javax.swing.JComboBox<>();
        CLASSATTENDENCE = new javax.swing.JComboBox<>();
        LabelLecturerID3 = new javax.swing.JLabel();
        LabelLecturerID4 = new javax.swing.JLabel();
        MODULENAME = new javax.swing.JComboBox<>();
        LabelLecturerID8 = new javax.swing.JLabel();
        CLEARATTENDENCE = new javax.swing.JButton();
        LabelLecturerID10 = new javax.swing.JLabel();
        LabelLecturerID9 = new javax.swing.JLabel();
        ATTENDENCEID = new javax.swing.JTextField();
        LabelLecturerDOB8 = new javax.swing.JLabel();
        UPDATESTUDENTATTENDENCE = new javax.swing.JButton();
        LabelLecturerDOB9 = new javax.swing.JLabel();
        CLEARSTUDENT3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        btnLecturerExit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BACK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(36, 47, 65));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID NO:", "NAME:", "GENDER:", "START CLASS:", "DURATION CLASS: ", "ATTENDENCE", "MODULE NAME", "DAY", "MONTH", "YEAR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable3AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 860, 190));

        LabelLecturerDOB7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelLecturerDOB7.setText("VIEW");
        jPanel2.add(LabelLecturerDOB7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 60, 30));

        LabelLecturerDOB6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelLecturerDOB6.setText("CLEAR");
        jPanel2.add(LabelLecturerDOB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 60, 30));

        CLEARSTUDENTATTENDENCE.setBackground(new java.awt.Color(97, 212, 195));
        CLEARSTUDENTATTENDENCE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CLEARSTUDENTATTENDENCE.setForeground(new java.awt.Color(102, 102, 102));
        CLEARSTUDENTATTENDENCE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture15.PNG"))); // NOI18N
        CLEARSTUDENTATTENDENCE.setText("SAVE");
        CLEARSTUDENTATTENDENCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARSTUDENTATTENDENCEActionPerformed(evt);
            }
        });
        jPanel2.add(CLEARSTUDENTATTENDENCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 120, 30));

        VIEWSTUDENTATTENDENCE.setBackground(new java.awt.Color(97, 212, 195));
        VIEWSTUDENTATTENDENCE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        VIEWSTUDENTATTENDENCE.setForeground(new java.awt.Color(102, 102, 102));
        VIEWSTUDENTATTENDENCE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture15.PNG"))); // NOI18N
        VIEWSTUDENTATTENDENCE.setText("SAVE");
        VIEWSTUDENTATTENDENCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VIEWSTUDENTATTENDENCEActionPerformed(evt);
            }
        });
        jPanel2.add(VIEWSTUDENTATTENDENCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 120, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Press, View button to see all records of Students' Attendence, & den Modify.");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 490, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setText("NOTE: Press Clear button to clear this table before go to view another time.");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 510, -1));

        jPanel3.setBackground(new java.awt.Color(36, 47, 65));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MODIFY STUDENT ATTENDENCE RECORD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(36, 47, 65));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelLecturerID5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelLecturerID5.setForeground(new java.awt.Color(204, 204, 204));
        LabelLecturerID5.setText("DATE:");
        jPanel4.add(LabelLecturerID5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 32));

        DATE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        DATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DATEActionPerformed(evt);
            }
        });
        jPanel4.add(DATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 90, -1));

        LabelLecturerID6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelLecturerID6.setForeground(new java.awt.Color(204, 204, 204));
        LabelLecturerID6.setText("MONTH:");
        jPanel4.add(LabelLecturerID6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, 32));

        MONTH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "JAN", "FEB", "MAR", "APRIL", "MAY", "JUNE", "JULY", "AUG", "SEP", "OCT", "NOV", "DEC" }));
        jPanel4.add(MONTH, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 90, -1));

        YEAR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "2017", "2018" }));
        jPanel4.add(YEAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 90, -1));

        LabelLecturerID7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelLecturerID7.setForeground(new java.awt.Color(204, 204, 204));
        LabelLecturerID7.setText("YEAR:");
        jPanel4.add(LabelLecturerID7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, 32));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 400, 80));

        LabelLecturerName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelLecturerName.setForeground(new java.awt.Color(204, 204, 204));
        LabelLecturerName.setText("GENDER:");
        jPanel3.add(LabelLecturerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 80, 30));

        ATTENDENCEGENDER.setEditable(false);
        ATTENDENCEGENDER.setBackground(new java.awt.Color(36, 47, 65));
        ATTENDENCEGENDER.setForeground(new java.awt.Color(255, 255, 255));
        ATTENDENCEGENDER.setToolTipText("");
        ATTENDENCEGENDER.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ATTENDENCEGENDER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ATTENDENCEGENDERActionPerformed(evt);
            }
        });
        jPanel3.add(ATTENDENCEGENDER, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 120, 30));

        ATTENDENSENAME.setEditable(false);
        ATTENDENSENAME.setBackground(new java.awt.Color(36, 47, 65));
        ATTENDENSENAME.setForeground(new java.awt.Color(255, 255, 255));
        ATTENDENSENAME.setToolTipText("");
        ATTENDENSENAME.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ATTENDENSENAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ATTENDENSENAMEActionPerformed(evt);
            }
        });
        jPanel3.add(ATTENDENSENAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 150, 30));

        CLASSTART.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "8:00AM", "9:00AM", "10:00AM", "11:00AM", "12:00AM", "1:00PM", "2:00PM", "3:00PM", "4:00PM", "5:00PM", "6:00PM", "7:00PM", "8:00PM" }));
        CLASSTART.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLASSTARTActionPerformed(evt);
            }
        });
        jPanel3.add(CLASSTART, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 90, -1));

        LabelLecturerID1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelLecturerID1.setText("SAVE RECORD");
        jPanel3.add(LabelLecturerID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 100, 30));

        LabelLecturerID2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelLecturerID2.setForeground(new java.awt.Color(204, 204, 204));
        LabelLecturerID2.setText("CLASS DURATION:");
        jPanel3.add(LabelLecturerID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, 32));

        CLASSDURATION.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "1 Hour", "2 Hour", "3 Hour" }));
        CLASSDURATION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLASSDURATIONActionPerformed(evt);
            }
        });
        jPanel3.add(CLASSDURATION, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 110, -1));

        CLASSATTENDENCE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "PRESENT", "ABSENT", "LATE" }));
        jPanel3.add(CLASSATTENDENCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 90, -1));

        LabelLecturerID3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelLecturerID3.setForeground(new java.awt.Color(204, 204, 204));
        LabelLecturerID3.setText("ATTENDENCE:");
        jPanel3.add(LabelLecturerID3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, -1, 32));

        LabelLecturerID4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelLecturerID4.setForeground(new java.awt.Color(204, 204, 204));
        LabelLecturerID4.setText("MODULE:");
        jPanel3.add(LabelLecturerID4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, 140, 32));

        MODULENAME.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "JAVA", "C-PROGRAMING", "SYSTEM NETWORKING", "COMPUTER THEORY", "MOBILE WIRELESS", "BHASA MALAYU" }));
        jPanel3.add(MODULENAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 100, -1));

        LabelLecturerID8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelLecturerID8.setForeground(new java.awt.Color(204, 204, 204));
        LabelLecturerID8.setText("STUDENT NAME: ");
        jPanel3.add(LabelLecturerID8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 100, 32));

        CLEARATTENDENCE.setBackground(new java.awt.Color(97, 212, 195));
        CLEARATTENDENCE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CLEARATTENDENCE.setForeground(new java.awt.Color(102, 102, 102));
        CLEARATTENDENCE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture15.PNG"))); // NOI18N
        CLEARATTENDENCE.setText("SAVE");
        CLEARATTENDENCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARATTENDENCEActionPerformed(evt);
            }
        });
        jPanel3.add(CLEARATTENDENCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 130, 30));

        LabelLecturerID10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelLecturerID10.setForeground(new java.awt.Color(204, 204, 204));
        LabelLecturerID10.setText("CLASS START:");
        jPanel3.add(LabelLecturerID10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 32));

        LabelLecturerID9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelLecturerID9.setForeground(new java.awt.Color(204, 204, 204));
        LabelLecturerID9.setText("STUDENT ID: ");
        jPanel3.add(LabelLecturerID9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 90, 32));

        ATTENDENCEID.setEditable(false);
        ATTENDENCEID.setBackground(new java.awt.Color(36, 47, 65));
        ATTENDENCEID.setForeground(new java.awt.Color(255, 255, 255));
        ATTENDENCEID.setToolTipText("");
        ATTENDENCEID.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ATTENDENCEID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ATTENDENCEIDActionPerformed(evt);
            }
        });
        jPanel3.add(ATTENDENCEID, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 120, 30));

        LabelLecturerDOB8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelLecturerDOB8.setText("UPDATE");
        jPanel3.add(LabelLecturerDOB8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 70, 30));

        UPDATESTUDENTATTENDENCE.setBackground(new java.awt.Color(97, 212, 195));
        UPDATESTUDENTATTENDENCE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UPDATESTUDENTATTENDENCE.setForeground(new java.awt.Color(102, 102, 102));
        UPDATESTUDENTATTENDENCE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture15.PNG"))); // NOI18N
        UPDATESTUDENTATTENDENCE.setText("SAVE");
        UPDATESTUDENTATTENDENCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATESTUDENTATTENDENCEActionPerformed(evt);
            }
        });
        jPanel3.add(UPDATESTUDENTATTENDENCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 120, 30));

        LabelLecturerDOB9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelLecturerDOB9.setText("CLEAR");
        jPanel3.add(LabelLecturerDOB9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, 50, 30));

        CLEARSTUDENT3.setBackground(new java.awt.Color(97, 212, 195));
        CLEARSTUDENT3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CLEARSTUDENT3.setForeground(new java.awt.Color(102, 102, 102));
        CLEARSTUDENT3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture15.PNG"))); // NOI18N
        CLEARSTUDENT3.setText("SAVE");
        CLEARSTUDENT3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARSTUDENT3ActionPerformed(evt);
            }
        });
        jPanel3.add(CLEARSTUDENT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 120, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 860, 240));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 940, 610));

        jPanel1.setBackground(new java.awt.Color(97, 212, 195));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MODIFY ATTENDENCE: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 270, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 250, 40));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 320, 40));

        btnLecturerExit.setText("EXIT");
        btnLecturerExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLecturerExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnLecturerExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 130, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("APU ATTENDENCE ");
        jLabel4.setToolTipText("");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("MANAGMENT SYSTEM");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/002-professor.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        BACK.setText("BACK");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });
        jPanel1.add(BACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 570, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        ATTENDENSENAME.setText(model.getValueAt(jTable3.getSelectedRow(),1).toString());
        ATTENDENCEID.setText(model.getValueAt(jTable3.getSelectedRow(),0).toString());
        ATTENDENCEGENDER.setText(model.getValueAt(jTable3.getSelectedRow(),2).toString());
        CLASSTART.setSelectedItem(model.getValueAt(jTable3.getSelectedRow(),3).toString());
        CLASSDURATION.setSelectedItem(model.getValueAt(jTable3.getSelectedRow(),4).toString());
        CLASSATTENDENCE.setSelectedItem(model.getValueAt(jTable3.getSelectedRow(),5).toString());
        MODULENAME.setSelectedItem(model.getValueAt(jTable3.getSelectedRow(),6).toString());
        DATE.setSelectedItem(model.getValueAt(jTable3.getSelectedRow(),7).toString());
        MONTH.setSelectedItem(model.getValueAt(jTable3.getSelectedRow(),8).toString());
        YEAR.setSelectedItem(model.getValueAt(jTable3.getSelectedRow(),9).toString());
        
    }//GEN-LAST:event_jTable3MouseClicked

    private void btnLecturerExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLecturerExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnLecturerExitActionPerformed

    private void CLEARSTUDENTATTENDENCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARSTUDENTATTENDENCEActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_CLEARSTUDENTATTENDENCEActionPerformed

    private void VIEWSTUDENTATTENDENCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VIEWSTUDENTATTENDENCEActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        //Lecturer1 lecturer = new Lecturer1();
        try{
            FileReader f=new FileReader("ATTENDENCERECORD.txt");
            BufferedReader bf=new BufferedReader(f);
            String line;
            while((line=bf.readLine())!=null){
                ATTENDENCESTUDENT student = new ATTENDENCESTUDENT(line);
                model.addRow(line.split(","));
                //model.addRow(new Object[]{lecturer.getidno(), lecturer.getname(), lecturer.getpassword(), lecturer.getgender(), lecturer.getnationality(), lecturer.getdob()});
            }
            bf.close();
        }catch(Exception e){}
    }//GEN-LAST:event_VIEWSTUDENTATTENDENCEActionPerformed

    private void ATTENDENCEGENDERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ATTENDENCEGENDERActionPerformed

    }//GEN-LAST:event_ATTENDENCEGENDERActionPerformed

    private void ATTENDENSENAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ATTENDENSENAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ATTENDENSENAMEActionPerformed

    private void CLASSTARTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLASSTARTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CLASSTARTActionPerformed

    private void CLASSDURATIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLASSDURATIONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CLASSDURATIONActionPerformed

    private void CLEARATTENDENCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARATTENDENCEActionPerformed
      
    }//GEN-LAST:event_CLEARATTENDENCEActionPerformed

    private void ATTENDENCEIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ATTENDENCEIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ATTENDENCEIDActionPerformed

    private void UPDATESTUDENTATTENDENCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATESTUDENTATTENDENCEActionPerformed
            String classstart=(String) CLASSTART.getSelectedItem();;
            String classduration =(String) CLASSDURATION.getSelectedItem();;
            String classattendence = (String) CLASSATTENDENCE.getSelectedItem();;
            String classmodule = (String) MODULENAME.getSelectedItem();;
            String classdate = (String) DATE.getSelectedItem();;
            String classmonth = (String) MONTH.getSelectedItem();;
            String classyear =(String) YEAR.getSelectedItem();;
            String classname = ATTENDENSENAME.getText();
            String classid = ATTENDENCEID.getText();
            String classgender = ATTENDENCEGENDER.getText();
        
        ArrayList<ATTENDENCESTUDENT> Studentrecord = new ArrayList<>();
     
        if (classstart.isEmpty() || classduration.isEmpty() || classattendence.isEmpty() || classmodule.isEmpty() || classdate.isEmpty() 
                || classmonth.isEmpty() || classyear.isEmpty() || classname.isEmpty() || classid.isEmpty() || classgender.isEmpty() ) {
            JOptionPane.showMessageDialog(this, " Please Fill all fields");}
        else{
        try {
            File f = new File ("ATTENDENCERECORD.txt");
            FileReader fr = new FileReader(f);
            BufferedReader br = new BufferedReader(fr);
            String data;
            ATTENDENCESTUDENT UpdateStudent;
            
            while ((data = br.readLine()) != null) {
                        UpdateStudent = new ATTENDENCESTUDENT(data);
                        if (UpdateStudent.getAId().equals(classid) &&UpdateStudent.getADate().equals(classdate) && UpdateStudent.getAMonth().equals(classmonth)&& UpdateStudent.getAYear().equals(classyear)) {
                            UpdateStudent.setAName(classname);
                            UpdateStudent.setAGender(classgender);
                            UpdateStudent.setAClassStart(classstart);
                            UpdateStudent.setAClassDuration(classduration);
                            UpdateStudent.setAClassAttendence(classattendence);
                            UpdateStudent.setAModuleName(classmodule);  
                            UpdateStudent.setADate(classdate);
                            UpdateStudent.setAMonth(classmonth);
                            UpdateStudent.setAYear(classyear);  
                            
                             }
                        Studentrecord.add(UpdateStudent);
                    }
            try (PrintWriter printwriter = new PrintWriter(new FileWriter(f, false))) {
                    Studentrecord.forEach((student) -> {
                        printwriter.println(student.toString());
                        
                        
                    });
                    JOptionPane.showMessageDialog(this, "Student Updated Succesfully");
                    
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }

            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
        
              }   catch (IOException ex) { 
                    Logger.getLogger(MODIFYSTUDENT.class.getName()).log(Level.SEVERE, null, ex);
                } 
        } 
    }//GEN-LAST:event_UPDATESTUDENTATTENDENCEActionPerformed

    private void CLEARSTUDENT3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARSTUDENT3ActionPerformed
    ATTENDENCEID.setText("");
        ATTENDENSENAME.setText("");
        ATTENDENCEGENDER.setText("");
        CLASSDURATION.setSelectedItem("SELECT");
        CLASSTART.setSelectedItem("SELECT");
        CLASSATTENDENCE.setSelectedItem("SELECT");
        MODULENAME.setSelectedItem("SELECT");
        DATE.setSelectedItem("SELECT");
        MONTH.setSelectedItem("SELECT");
        YEAR.setSelectedItem("SELECT");        // TODO add your handling code here:
    }//GEN-LAST:event_CLEARSTUDENT3ActionPerformed

    private void DATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DATEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DATEActionPerformed

    private void jTable3AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable3AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable3AncestorAdded

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
        close();
        TEACHERINFORMATION goback = new TEACHERINFORMATION();
        goback.setVisible(true);
    }//GEN-LAST:event_BACKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TEACHERMODIFYSTUDENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TEACHERMODIFYSTUDENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TEACHERMODIFYSTUDENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TEACHERMODIFYSTUDENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TEACHERMODIFYSTUDENT().setVisible(true);
            }
        });
    }
    private void close() {
        WindowEvent closewindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closewindow);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ATTENDENCEGENDER;
    private javax.swing.JTextField ATTENDENCEID;
    private javax.swing.JTextField ATTENDENSENAME;
    private javax.swing.JButton BACK;
    private javax.swing.JComboBox<String> CLASSATTENDENCE;
    private javax.swing.JComboBox<String> CLASSDURATION;
    private javax.swing.JComboBox<String> CLASSTART;
    private javax.swing.JButton CLEARATTENDENCE;
    private javax.swing.JButton CLEARSTUDENT3;
    private javax.swing.JButton CLEARSTUDENTATTENDENCE;
    private javax.swing.JComboBox<String> DATE;
    private javax.swing.JLabel LabelLecturerDOB6;
    private javax.swing.JLabel LabelLecturerDOB7;
    private javax.swing.JLabel LabelLecturerDOB8;
    private javax.swing.JLabel LabelLecturerDOB9;
    private javax.swing.JLabel LabelLecturerID1;
    private javax.swing.JLabel LabelLecturerID10;
    private javax.swing.JLabel LabelLecturerID2;
    private javax.swing.JLabel LabelLecturerID3;
    private javax.swing.JLabel LabelLecturerID4;
    private javax.swing.JLabel LabelLecturerID5;
    private javax.swing.JLabel LabelLecturerID6;
    private javax.swing.JLabel LabelLecturerID7;
    private javax.swing.JLabel LabelLecturerID8;
    private javax.swing.JLabel LabelLecturerID9;
    private javax.swing.JLabel LabelLecturerName;
    private javax.swing.JComboBox<String> MODULENAME;
    private javax.swing.JComboBox<String> MONTH;
    private javax.swing.JButton UPDATESTUDENTATTENDENCE;
    private javax.swing.JButton VIEWSTUDENTATTENDENCE;
    private javax.swing.JComboBox<String> YEAR;
    private javax.swing.JButton btnLecturerExit;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
