
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bunny_Mangrani
 */
public class TEACHERVIEWSTUDENT extends javax.swing.JFrame {

    /**
     * Creates new form TEACHERVIEWSTUDENT
     */
    public TEACHERVIEWSTUDENT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BACK = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        btnLecturerExit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        VIEWINTAKE = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        LabelLecturerDOB5 = new javax.swing.JLabel();
        VIEWSTUEDNT = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        LabelLecturerDOB6 = new javax.swing.JLabel();
        CLEARSTUDENT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(97, 212, 195));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BACK.setText("BACK");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });
        jPanel1.add(BACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, 130, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("VIEW INTAKEVISE STUDENT: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 270, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/002-professor.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 250, 40));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 320, 40));

        btnLecturerExit.setText("EXIT");
        btnLecturerExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLecturerExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnLecturerExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 130, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("APU ATTENDENCE ");
        jLabel4.setToolTipText("");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("MANAGMENT SYSTEM");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 560));

        jPanel4.setBackground(new java.awt.Color(36, 47, 65));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("NOTE: Press \"CLEAR\" button to clear this table before go to view another intake students.");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 560, -1));

        VIEWINTAKE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Intake", "UC2F1704CS", "UC2F1704IT", "UC2F1704BDS" }));
        jPanel4.add(VIEWINTAKE, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 100, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID NO:", "NAME:", "NATIONALITY:", "GENDER:", "DOB:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 570, 350));

        LabelLecturerDOB5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelLecturerDOB5.setText("VIEW STUDENT");
        jPanel4.add(LabelLecturerDOB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 110, 30));

        VIEWSTUEDNT.setBackground(new java.awt.Color(97, 212, 195));
        VIEWSTUEDNT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        VIEWSTUEDNT.setForeground(new java.awt.Color(102, 102, 102));
        VIEWSTUEDNT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture15.PNG"))); // NOI18N
        VIEWSTUEDNT.setText("SAVE");
        VIEWSTUEDNT.setBorder(null);
        VIEWSTUEDNT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VIEWSTUEDNTActionPerformed(evt);
            }
        });
        jPanel4.add(VIEWSTUEDNT, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 140, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("PLEASE SELECT THE INTAKE:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 230, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("PLEASE SELECT THE INTAKE & Click VIEW STUDENT:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 380, -1));

        LabelLecturerDOB6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelLecturerDOB6.setText("CLEAR STUDENT");
        jPanel4.add(LabelLecturerDOB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 120, 30));

        CLEARSTUDENT.setBackground(new java.awt.Color(97, 212, 195));
        CLEARSTUDENT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CLEARSTUDENT.setForeground(new java.awt.Color(102, 102, 102));
        CLEARSTUDENT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture15.PNG"))); // NOI18N
        CLEARSTUDENT.setText("SAVE");
        CLEARSTUDENT.setBorder(null);
        CLEARSTUDENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARSTUDENTActionPerformed(evt);
            }
        });
        jPanel4.add(CLEARSTUDENT, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 140, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 660, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents
     private void CLEARSTUDENTActionPerformed(java.awt.event.ActionEvent evt) { 
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         model.setRowCount(0);
         
        
    }    
    private void btnLecturerExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLecturerExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnLecturerExitActionPerformed
    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {                                     
        close();
        TEACHERINFORMATION goback = new TEACHERINFORMATION();
        goback.setVisible(true);
    }  
    private void VIEWSTUEDNTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VIEWSTUEDNTActionPerformed
        switch ((String) VIEWINTAKE.getSelectedItem()) {
                        case "UC2F1704CS":
            
            
           try{
               
               File file = new File("Student.txt");
               BufferedReader bf = new BufferedReader(new FileReader(file));
               String line;
               while((line = bf.readLine())!= null){
                   Student1 course = new Student1(line);
                   if(course.getIntake().equals("UC2F1704CS")){
                   DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                   model.addRow(line.split(",")); }
                   
                   }
                   bf.close();
               
           } catch(Exception e) {JOptionPane.showMessageDialog(null,e);}                            
             
           break;
           
           
                        case "UC2F1704IT":
                        
                        
                        
                        
            try{
               File file = new File("Student.txt");
               BufferedReader bf = new BufferedReader(new FileReader(file));
               String line;
               while((line = bf.readLine())!= null){
                   Student1 course = new Student1(line);
                   if(course.getIntake().equals("UC2F1704IT")){
                   DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                   model.addRow(line.split(",")); }
                   
                   }
                   bf.close();
               
           } catch(Exception e) {JOptionPane.showMessageDialog(null,e);}                            
             
           break;
           
                                case "UC2F1704BDS":
            
                        
            try{
               File file = new File("Student.txt");
               BufferedReader bf = new BufferedReader(new FileReader(file));
               String line;
               while((line = bf.readLine())!= null){
                   Student1 course = new Student1(line);
                   if(course.getIntake().equals("UC2F1704BDS")){
                   DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                   model.addRow(line.split(",")); }
                   
                   }
                   bf.close();
               
           } catch(Exception e) {JOptionPane.showMessageDialog(null,e);}                            
             
           break;
           
           default : 
                     JOptionPane.showMessageDialog(null,"Please select a user type","Warning", JOptionPane.ERROR_MESSAGE);
                      break; 
                            
                            
                            
                            
                            
                            
                            
                            
                            
    }//GEN-LAST:event_VIEWSTUEDNTActionPerformed
/*
    private void CLEARSTUDENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARSTUDENTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CLEARSTUDENTActionPerformed

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
        close();
        ADMININFORMATION goback = new ADMININFORMATION();
        goback.setVisible(true);
    }//GEN-LAST:event_BACKActionPerformed

    */    
        
        
        
    }
     private void close() {
        WindowEvent closewindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closewindow);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TEACHERVIEWSTUDENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TEACHERVIEWSTUDENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TEACHERVIEWSTUDENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TEACHERVIEWSTUDENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TEACHERVIEWSTUDENT().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACK;
    private javax.swing.JButton CLEARSTUDENT;
    private javax.swing.JLabel LabelLecturerDOB5;
    private javax.swing.JLabel LabelLecturerDOB6;
    private javax.swing.JComboBox<String> VIEWINTAKE;
    private javax.swing.JButton VIEWSTUEDNT;
    private javax.swing.JButton btnLecturerExit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
