
import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bunny_Mangrani
 */
public class TEACHERINFORMATION extends javax.swing.JFrame {

    /**
     * Creates new form TEACHERINFORMATION
     */
    public TEACHERINFORMATION() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        VIEWINTAKEVISESTUDNET = new javax.swing.JButton();
        TAKEATTENDENCE = new javax.swing.JButton();
        MODIFYATTENDENCE = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        BACK = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("WELCOME.... ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 300, -1));

        VIEWINTAKEVISESTUDNET.setText("VIEW INTAKEVISE STUDENT");
        VIEWINTAKEVISESTUDNET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VIEWINTAKEVISESTUDNETActionPerformed(evt);
            }
        });
        getContentPane().add(VIEWINTAKEVISESTUDNET, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 200, 40));

        TAKEATTENDENCE.setText("TAKE ATTENDENCE");
        TAKEATTENDENCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TAKEATTENDENCEActionPerformed(evt);
            }
        });
        getContentPane().add(TAKEATTENDENCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 200, 40));

        MODIFYATTENDENCE.setText("MODIFY ATTENDENCE");
        MODIFYATTENDENCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MODIFYATTENDENCEActionPerformed(evt);
            }
        });
        getContentPane().add(MODIFYATTENDENCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 200, 40));

        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 130, -1));

        BACK.setText("BACK");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });
        getContentPane().add(BACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 130, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apu_still01_entrance_0.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VIEWINTAKEVISESTUDNETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VIEWINTAKEVISESTUDNETActionPerformed
        TEACHERVIEWSTUDENT student= new TEACHERVIEWSTUDENT ();
        student.setVisible(true);
    }//GEN-LAST:event_VIEWINTAKEVISESTUDNETActionPerformed

    private void TAKEATTENDENCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TAKEATTENDENCEActionPerformed
        TEACHERATTENDENCE student= new TEACHERATTENDENCE ();
        student.setVisible(true);

    }//GEN-LAST:event_TAKEATTENDENCEActionPerformed

    private void MODIFYATTENDENCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODIFYATTENDENCEActionPerformed
        TEACHERMODIFYSTUDENT student= new TEACHERMODIFYSTUDENT ();
        student.setVisible(true);

    }//GEN-LAST:event_MODIFYATTENDENCEActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
        close();
        LECTURERLOGINFORM goback = new LECTURERLOGINFORM();
        goback.setVisible(true);
    }//GEN-LAST:event_BACKActionPerformed
    private void close() {
        WindowEvent closewindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closewindow);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TEACHERINFORMATION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TEACHERINFORMATION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TEACHERINFORMATION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TEACHERINFORMATION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TEACHERINFORMATION().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACK;
    private javax.swing.JButton MODIFYATTENDENCE;
    private javax.swing.JButton TAKEATTENDENCE;
    private javax.swing.JButton VIEWINTAKEVISESTUDNET;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
