
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bunny_Mangrani
 */
public class TEACHERATTENDENCE extends javax.swing.JFrame {

    /**
     * Creates new form TEACHERATTENDENCE
     */
    public TEACHERATTENDENCE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        btnLecturerExit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BACK = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        VIEWINTAKE = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        LabelLecturerDOB5 = new javax.swing.JLabel();
        VIEWSTUEDNT = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        LabelLecturerDOB6 = new javax.swing.JLabel();
        CLEARSTUDENT = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        LabelLecturerID5 = new javax.swing.JLabel();
        DATE = new javax.swing.JComboBox<>();
        LabelLecturerID6 = new javax.swing.JLabel();
        MONTH = new javax.swing.JComboBox<>();
        YEAR = new javax.swing.JComboBox<>();
        LabelLecturerID7 = new javax.swing.JLabel();
        LabelLecturerName = new javax.swing.JLabel();
        ATTENDENCEGENDER = new javax.swing.JTextField();
        LabelLecturerID = new javax.swing.JLabel();
        ATTENDENSENAME = new javax.swing.JTextField();
        CLASSSTART = new javax.swing.JComboBox<>();
        LabelLecturerID1 = new javax.swing.JLabel();
        LabelLecturerID2 = new javax.swing.JLabel();
        CLASSDURATION = new javax.swing.JComboBox<>();
        CLASSATTENDENCE = new javax.swing.JComboBox<>();
        LabelLecturerID3 = new javax.swing.JLabel();
        LabelLecturerID4 = new javax.swing.JLabel();
        MODULENAME = new javax.swing.JComboBox<>();
        LabelLecturerID8 = new javax.swing.JLabel();
        SAVESTUDENT = new javax.swing.JButton();
        CLEARATTENDENCE = new javax.swing.JButton();
        LabelLecturerID10 = new javax.swing.JLabel();
        LabelLecturerID9 = new javax.swing.JLabel();
        ATTENDENCEID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(97, 212, 195));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TAKE ATTENDENCE:  ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 220, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/002-professor.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 200, 40));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 270, 40));

        btnLecturerExit.setText("EXIT");
        btnLecturerExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLecturerExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnLecturerExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 130, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("APU ATTENDENCE ");
        jLabel4.setToolTipText("");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("MANAGMENT SYSTEM");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        BACK.setText("BACK");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });
        jPanel1.add(BACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 530));

        jPanel4.setBackground(new java.awt.Color(36, 47, 65));
        jPanel4.setForeground(new java.awt.Color(204, 204, 204));
        jPanel4.setToolTipText("");
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        VIEWINTAKE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Intake", "UC2F1704CS", "UC2F1704IT", "UC2F1704BDS" }));
        jPanel4.add(VIEWINTAKE, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 120, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID NO:", "NAME:", "PASS:", "DOB:", "NATIONALITY:", "GENDER: "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 370, 280));

        LabelLecturerDOB5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelLecturerDOB5.setText("VIEW STUDENT");
        jPanel4.add(LabelLecturerDOB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 110, 30));

        VIEWSTUEDNT.setBackground(new java.awt.Color(97, 212, 195));
        VIEWSTUEDNT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        VIEWSTUEDNT.setForeground(new java.awt.Color(102, 102, 102));
        VIEWSTUEDNT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture15.PNG"))); // NOI18N
        VIEWSTUEDNT.setText("SAVE");
        VIEWSTUEDNT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VIEWSTUEDNTActionPerformed(evt);
            }
        });
        jPanel4.add(VIEWSTUEDNT, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 130, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("PLEASE SELECT THE INTAKE:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 230, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("PLEASE SELECT THE INTAKE & Click VIEW STUDENT:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 380, -1));

        LabelLecturerDOB6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelLecturerDOB6.setText("CLEAR");
        jPanel4.add(LabelLecturerDOB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 60, 30));

        CLEARSTUDENT.setBackground(new java.awt.Color(97, 212, 195));
        CLEARSTUDENT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CLEARSTUDENT.setForeground(new java.awt.Color(102, 102, 102));
        CLEARSTUDENT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture15.PNG"))); // NOI18N
        CLEARSTUDENT.setText("SAVE");
        CLEARSTUDENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARSTUDENTActionPerformed(evt);
            }
        });
        jPanel4.add(CLEARSTUDENT, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 120, 30));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 370, 10));

        jPanel2.setBackground(new java.awt.Color(36, 47, 65));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TAKE ATTENDENCE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(36, 47, 65));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelLecturerID5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelLecturerID5.setForeground(new java.awt.Color(204, 204, 204));
        LabelLecturerID5.setText("DATE:");
        jPanel3.add(LabelLecturerID5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 32));

        DATE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel3.add(DATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 90, -1));

        LabelLecturerID6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelLecturerID6.setForeground(new java.awt.Color(204, 204, 204));
        LabelLecturerID6.setText("MONTH:");
        jPanel3.add(LabelLecturerID6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, 32));

        MONTH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "JAN", "FEB", "MAR", "APRIL", "MAY", "JUNE", "JULY", "AUG", "SEP", "OCT", "NOV", "DEC" }));
        jPanel3.add(MONTH, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 90, -1));

        YEAR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "2017", "2018" }));
        jPanel3.add(YEAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 90, -1));

        LabelLecturerID7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelLecturerID7.setForeground(new java.awt.Color(204, 204, 204));
        LabelLecturerID7.setText("YEAR:");
        jPanel3.add(LabelLecturerID7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, 32));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 400, 80));

        LabelLecturerName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelLecturerName.setForeground(new java.awt.Color(204, 204, 204));
        LabelLecturerName.setText("GENDER:");
        jPanel2.add(LabelLecturerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 80, 30));

        ATTENDENCEGENDER.setBackground(new java.awt.Color(36, 47, 65));
        ATTENDENCEGENDER.setForeground(new java.awt.Color(255, 255, 255));
        ATTENDENCEGENDER.setToolTipText("");
        ATTENDENCEGENDER.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ATTENDENCEGENDER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ATTENDENCEGENDERActionPerformed(evt);
            }
        });
        jPanel2.add(ATTENDENCEGENDER, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 120, 30));

        LabelLecturerID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelLecturerID.setText("CLEAR");
        jPanel2.add(LabelLecturerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, -1, 30));

        ATTENDENSENAME.setBackground(new java.awt.Color(36, 47, 65));
        ATTENDENSENAME.setForeground(new java.awt.Color(255, 255, 255));
        ATTENDENSENAME.setToolTipText("");
        ATTENDENSENAME.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ATTENDENSENAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ATTENDENSENAMEActionPerformed(evt);
            }
        });
        jPanel2.add(ATTENDENSENAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 320, 30));

        CLASSSTART.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "8:00AM", "9:00AM", "10:00AM", "11:00AM", "12:00AM", "1:00PM", "2:00PM", "3:00PM", "4:00PM", "5:00PM", "6:00PM", "7:00PM", "8:00PM" }));
        CLASSSTART.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLASSSTARTActionPerformed(evt);
            }
        });
        jPanel2.add(CLASSSTART, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 90, -1));

        LabelLecturerID1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelLecturerID1.setText("SAVE RECORD");
        jPanel2.add(LabelLecturerID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 100, 30));

        LabelLecturerID2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelLecturerID2.setForeground(new java.awt.Color(204, 204, 204));
        LabelLecturerID2.setText("CLASS DURATION:");
        jPanel2.add(LabelLecturerID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, 32));

        CLASSDURATION.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "1 Hour", "2 Hour", "3 Hour" }));
        CLASSDURATION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLASSDURATIONActionPerformed(evt);
            }
        });
        jPanel2.add(CLASSDURATION, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 110, -1));

        CLASSATTENDENCE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "PRESENT", "ABSENT", "LATE" }));
        jPanel2.add(CLASSATTENDENCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 90, -1));

        LabelLecturerID3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelLecturerID3.setForeground(new java.awt.Color(204, 204, 204));
        LabelLecturerID3.setText("ATTENDENCE:");
        jPanel2.add(LabelLecturerID3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 32));

        LabelLecturerID4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelLecturerID4.setForeground(new java.awt.Color(204, 204, 204));
        LabelLecturerID4.setText("MODULE NAME: ");
        jPanel2.add(LabelLecturerID4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, 32));

        MODULENAME.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "JAVA", "C-PROGRAMING", "SYSTEM NETWORKING", "COMPUTER THEORY", "MOBILE WIRELESS", "BHASA MALAYU" }));
        jPanel2.add(MODULENAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 110, -1));

        LabelLecturerID8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelLecturerID8.setForeground(new java.awt.Color(204, 204, 204));
        LabelLecturerID8.setText("STUDENT NAME: ");
        jPanel2.add(LabelLecturerID8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 100, 32));

        SAVESTUDENT.setBackground(new java.awt.Color(97, 212, 195));
        SAVESTUDENT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SAVESTUDENT.setForeground(new java.awt.Color(102, 102, 102));
        SAVESTUDENT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture15.PNG"))); // NOI18N
        SAVESTUDENT.setText("SAVE");
        SAVESTUDENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVESTUDENTActionPerformed(evt);
            }
        });
        jPanel2.add(SAVESTUDENT, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 130, 30));

        CLEARATTENDENCE.setBackground(new java.awt.Color(97, 212, 195));
        CLEARATTENDENCE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CLEARATTENDENCE.setForeground(new java.awt.Color(102, 102, 102));
        CLEARATTENDENCE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capture15.PNG"))); // NOI18N
        CLEARATTENDENCE.setText("SAVE");
        CLEARATTENDENCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARATTENDENCEActionPerformed(evt);
            }
        });
        jPanel2.add(CLEARATTENDENCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 130, 30));

        LabelLecturerID10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelLecturerID10.setForeground(new java.awt.Color(204, 204, 204));
        LabelLecturerID10.setText("CLASS START:");
        jPanel2.add(LabelLecturerID10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 32));

        LabelLecturerID9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelLecturerID9.setForeground(new java.awt.Color(204, 204, 204));
        LabelLecturerID9.setText("STUDENT ID: ");
        jPanel2.add(LabelLecturerID9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 90, 32));

        ATTENDENCEID.setBackground(new java.awt.Color(36, 47, 65));
        ATTENDENCEID.setForeground(new java.awt.Color(255, 255, 255));
        ATTENDENCEID.setToolTipText("");
        ATTENDENCEID.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ATTENDENCEID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ATTENDENCEIDActionPerformed(evt);
            }
        });
        jPanel2.add(ATTENDENCEID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 120, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setText("NOTE: For Attendence, You need to go view student first, & Click   ");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("the student record, that you want to take the Attendence");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 480, 490));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setText("NOTE: Press \"CLEAR\" button to clear this table ");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setText("before go to view another record of intake. ");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 1000, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLecturerExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLecturerExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnLecturerExitActionPerformed
        private void CLASSDURATIONActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             
     private void CLASSSTARTActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          
    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {                                     
        close();
        TEACHERINFORMATION goback = new TEACHERINFORMATION();
        goback.setVisible(true);
    }
     private void close() {
        WindowEvent closewindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closewindow);
    }
    private void ATTENDENCEIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ATTENDENCEIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ATTENDENCEIDActionPerformed

    private void CLEARATTENDENCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARATTENDENCEActionPerformed
               ATTENDENCEID.setText("");
               ATTENDENSENAME.setText("");
               ATTENDENCEGENDER.setText("");
               CLASSDURATION.setSelectedItem("SELECT");
               CLASSSTART.setSelectedItem("SELECT");
               CLASSATTENDENCE.setSelectedItem("SELECT");
               MODULENAME.setSelectedItem("SELECT");
               DATE.setSelectedItem("SELECT");
               MONTH.setSelectedItem("SELECT");
               YEAR.setSelectedItem("SELECT");
               
    }//GEN-LAST:event_CLEARATTENDENCEActionPerformed

    private void SAVESTUDENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVESTUDENTActionPerformed
           
            String Name = ATTENDENSENAME.getText();
            String ID = ATTENDENCEID.getText();
            String gender = ATTENDENCEGENDER.getText();
            String classduration =(String) CLASSDURATION.getSelectedItem();
            String classstart =(String) CLASSSTART.getSelectedItem();
            String classattendence =(String) CLASSATTENDENCE.getSelectedItem();
            String modulename =(String) MODULENAME.getSelectedItem();
            String date =(String) DATE.getSelectedItem(); 
            String month =(String)MONTH.getSelectedItem(); 
            String year =(String)YEAR.getSelectedItem();
           
            if (ID.isEmpty() || Name.isEmpty() || gender.isEmpty() || classduration.isEmpty()|| classstart.isEmpty()
                || classattendence.isEmpty()|| modulename.isEmpty() || date.isEmpty() || month.isEmpty() || year.isEmpty() ) {
            JOptionPane.showMessageDialog(this, " Please Fill all  the fields first");}
            else{
           
                
                  ATTENDENCESTUDENT studentrecord = new ATTENDENCESTUDENT(ID, Name, gender, classstart, classduration, classattendence, modulename, date, month, year);
           
       try{
           boolean flag = false;
           File f = new File("ATTENDENCERECORD.txt");
           BufferedReader bf = new BufferedReader(new FileReader(f));
           PrintWriter fw = new PrintWriter(new FileWriter(f,true));
           String line = bf.readLine();
           while(line!=null){
           
           ATTENDENCESTUDENT record = new ATTENDENCESTUDENT(line);
           if(record.getAId().equals(ID)&&record.getAId().equals(date) && record.getAMonth().equals(month) && record.getAYear().equals(year)){
               flag = true;
           }
           line = bf.readLine();
           }
           if(!flag){
           fw.println(studentrecord.toString());
           fw.flush();
           JOptionPane.showMessageDialog(null, "Saved Successfully");
            
               ATTENDENCEID.setText("");
               ATTENDENSENAME.setText("");
               ATTENDENCEGENDER.setText("");
               CLASSSTART.setSelectedItem("SELECT");
               CLASSDURATION.setSelectedItem("SELECT");
               CLASSATTENDENCE.setSelectedItem("SELECT");
               MODULENAME.setSelectedItem("SELECT");
               DATE.setSelectedItem("SELECT");
               MONTH.setSelectedItem("SELECT");
               YEAR.setSelectedItem("SELECT");
               
           
           
    }
           else{JOptionPane.showMessageDialog(null, "YOU ALREADY TAKE THE ATTENDENCE OF THIS RECORD");}
               ATTENDENCEID.setText("");
               ATTENDENSENAME.setText("");
               ATTENDENCEGENDER.setText("");
               CLASSSTART.setSelectedItem("SELECT");
               CLASSDURATION.setSelectedItem("SELECT");
               CLASSATTENDENCE.setSelectedItem("SELECT");
               MODULENAME.setSelectedItem("SELECT");
               DATE.setSelectedItem("SELECT");
               MONTH.setSelectedItem("SELECT");
               YEAR.setSelectedItem("SELECT");
               
           
               bf.close();
               fw.close();
               
              
       }
       
        catch(IOException e) {
           JOptionPane.showMessageDialog (null, "I cannot create the file");
        }
            }
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        /*String Name = ATTENDENSENAME.getText();
            String ID = ATTENDENCEID.getText();
            String gender = ATTENDENCEGENDER.getText();
            String classduration =(String) CLASSDURATION.getSelectedItem();
            String classstart =(String) CLASSSTART.getSelectedItem();
            String classattendence =(String) CLASSATTENDENCE.getSelectedItem();
            String modulename =(String) MODULENAME.getSelectedItem();
            String date =(String) DATE.getSelectedItem(); 
            String month =(String)MONTH.getSelectedItem(); 
            String year =(String)YEAR.getSelectedItem();
           
            if (ID.isEmpty() || Name.isEmpty() || gender.isEmpty() || classduration.isEmpty()|| classstart.isEmpty()
                || classattendence.isEmpty()|| modulename.isEmpty() || date.isEmpty() || month.isEmpty() || year.isEmpty() ) {
            JOptionPane.showMessageDialog(this, " Please Fill all  the fields first");}
            else{
              JOptionPane.showMessageDialog(this, " Successfulll");
                
                  ATTENDENCESTUDENT studentrecord = new ATTENDENCESTUDENT(ID, Name, gender, classduration, classstart, classattendence, modulename, date, month, year);
           
       try{
           PrintWriter fw = new PrintWriter(new FileWriter("ATTENDENCERECORD.txt",true));
           fw.println(studentrecord.toString());
           fw.flush();
           
               JOptionPane.showMessageDialog(null, "Saved Successfully");
               
               fw.close();
               ATTENDENCEID.setText("");
               ATTENDENSENAME.setText("");
               ATTENDENCEGENDER.setText("");
               CLASSDURATION.setSelectedItem("SELECT");
               CLASSSTART.setSelectedItem("SELECT");
               CLASSATTENDENCE.setSelectedItem("SELECT");
               MODULENAME.setSelectedItem("SELECT");
               DATE.setSelectedItem("SELECT");
               MONTH.setSelectedItem("SELECT");
               YEAR.setSelectedItem("SELECT");
               
              
       }
       
        catch(IOException e) {
           JOptionPane.showMessageDialog (null, "I cannot create the file");
        }
            
            }
            */
    }//GEN-LAST:event_SAVESTUDENTActionPerformed

    private void ATTENDENSENAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ATTENDENSENAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ATTENDENSENAMEActionPerformed
  
    private void ATTENDENCEGENDERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ATTENDENCEGENDERActionPerformed

    }//GEN-LAST:event_ATTENDENCEGENDERActionPerformed
    
    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
    }
    private void CLEARSTUDENTActionPerformed(java.awt.event.ActionEvent evt) {                                             
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         model.setRowCount(0);
    } 
    
      private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        ATTENDENSENAME.setText(model.getValueAt(jTable1.getSelectedRow(),1).toString());
        ATTENDENCEID.setText(model.getValueAt(jTable1.getSelectedRow(),0).toString());
        ATTENDENCEGENDER.setText(model.getValueAt(jTable1.getSelectedRow(),5).toString());
      }
    /*
    private void CLEARSTUDENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARSTUDENTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CLEARSTUDENTActionPerformed
*/
    private void VIEWSTUEDNTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VIEWSTUEDNTActionPerformed
        switch ((String) VIEWINTAKE.getSelectedItem()) {
            case "UC2F1704CS":

            try{

                File file = new File("Student.txt");
                BufferedReader bf = new BufferedReader(new FileReader(file));
                String line;
                while((line = bf.readLine())!= null){
                    Student1 course = new Student1(line);
                    if(course.getIntake().equals("UC2F1704CS")){
                        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                        model.addRow(line.split(",")); }

                }
                bf.close();

            } catch(Exception e) {JOptionPane.showMessageDialog(null,e);}

            break;

            case "UC2F1704IT":

            try{
                File file = new File("Student.txt");
                BufferedReader bf = new BufferedReader(new FileReader(file));
                String line;
                while((line = bf.readLine())!= null){
                    Student1 course = new Student1(line);
                    if(course.getIntake().equals("UC2F1704IT")){
                        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                        model.addRow(line.split(",")); }

                }
                bf.close();

            } catch(Exception e) {JOptionPane.showMessageDialog(null,e);}

            break;

            case "UC2F1704BDS":

            try{
                File file = new File("Student.txt");
                BufferedReader bf = new BufferedReader(new FileReader(file));
                String line;
                while((line = bf.readLine())!= null){
                    Student1 course = new Student1(line);
                    if(course.getIntake().equals("UC2F1704BDS")){
                        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                        model.addRow(line.split(",")); }

                }
                bf.close();

            } catch(Exception e) {JOptionPane.showMessageDialog(null,e);}

            break;

            default :
            JOptionPane.showMessageDialog(null,"Please select a user type","Warning", JOptionPane.ERROR_MESSAGE);
            break;
    }//GEN-LAST:event_VIEWSTUEDNTActionPerformed
    }
//GEN-FIRST:event_jTable1MouseClicked
 
//GEN-LAST:event_jTable1MouseClicked
/*
    private void CLASSDURATIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLASSDURATIONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CLASSDURATIONActionPerformed
*/
/*
    private void CLASSSTARTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLASSSTARTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CLASSSTARTActionPerformed


    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BACKActionPerformed
            */
   /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TEACHERATTENDENCE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TEACHERATTENDENCE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TEACHERATTENDENCE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TEACHERATTENDENCE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TEACHERATTENDENCE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ATTENDENCEGENDER;
    private javax.swing.JTextField ATTENDENCEID;
    private javax.swing.JTextField ATTENDENSENAME;
    private javax.swing.JButton BACK;
    private javax.swing.JComboBox<String> CLASSATTENDENCE;
    private javax.swing.JComboBox<String> CLASSDURATION;
    private javax.swing.JComboBox<String> CLASSSTART;
    private javax.swing.JButton CLEARATTENDENCE;
    private javax.swing.JButton CLEARSTUDENT;
    private javax.swing.JComboBox<String> DATE;
    private javax.swing.JLabel LabelLecturerDOB5;
    private javax.swing.JLabel LabelLecturerDOB6;
    private javax.swing.JLabel LabelLecturerID;
    private javax.swing.JLabel LabelLecturerID1;
    private javax.swing.JLabel LabelLecturerID10;
    private javax.swing.JLabel LabelLecturerID2;
    private javax.swing.JLabel LabelLecturerID3;
    private javax.swing.JLabel LabelLecturerID4;
    private javax.swing.JLabel LabelLecturerID5;
    private javax.swing.JLabel LabelLecturerID6;
    private javax.swing.JLabel LabelLecturerID7;
    private javax.swing.JLabel LabelLecturerID8;
    private javax.swing.JLabel LabelLecturerID9;
    private javax.swing.JLabel LabelLecturerName;
    private javax.swing.JComboBox<String> MODULENAME;
    private javax.swing.JComboBox<String> MONTH;
    private javax.swing.JButton SAVESTUDENT;
    private javax.swing.JComboBox<String> VIEWINTAKE;
    private javax.swing.JButton VIEWSTUEDNT;
    private javax.swing.JComboBox<String> YEAR;
    private javax.swing.JButton btnLecturerExit;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
